export type C4SightAssetCategory =
  | 'main_world'
  | 'blackboard_mode'
  | 'interface_mode'
  | 'human_judgement_mode'
  | 'recurring_devices'
  | 'mascot_wizard'
  | 'host'
  | 'transitions'
  | 'audio_identity';

export type C4SightAssetFormat = 'svg' | 'png' | 'wav' | 'mp3';

export type C4SightAssetFallback =
  | 'MascotAssetPlaceholder'
  | 'PropAssetPlaceholder'
  | 'IconAssetPlaceholder'
  | 'CardAssetPlaceholder'
  | 'SceneKeyframePlaceholder'
  | 'TextureAssetPlaceholder'
  | 'EffectAssetPlaceholder'
  | 'ModeAssetPlaceholder'
  | 'TransitionAssetPlaceholder'
  | 'AudioAssetPlaceholder'
  | 'HostAssetPlaceholder'
  | 'RecurringDeviceAssetPlaceholder';

export type C4SightAssetDefinition = {
  id: string;
  displayName: string;
  category: C4SightAssetCategory;
  filePath: string;
  preferredFormat: C4SightAssetFormat;
  required: boolean;
  usageNotes: string;
  fallbackComponent: C4SightAssetFallback;
  episode1Minimum?: boolean;
};

export const c4sightAssetManifest = [
  {
    id: 'main_world.style_frame',
    displayName: 'Main Animated World style frame',
    category: 'main_world',
    filePath: '/c4sight/assets/main-world/style-frame.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Default non-blackboard visual world for hooks, metaphor, humour, and connective narration.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'main_world.environment_base',
    displayName: 'Main Animated World environment base',
    category: 'main_world',
    filePath: '/c4sight/assets/main-world/environment-base.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Base environment/background for the main animated world before board or interface modes appear.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'main_world.episode01_magic_question_styleframe',
    displayName: 'Episode 1 magic question styleframe',
    category: 'main_world',
    filePath: '/c4sight/assets/main-world/episode01-magic-question-styleframe.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Styleframe for the Episode 1 question: Is AI actually magic, or are we just bad at understanding it?',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'main_world.character_scale_reference',
    displayName: 'Main Animated World character scale reference',
    category: 'main_world',
    filePath: '/c4sight/assets/main-world/character-scale-reference.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Reference sheet showing host, recurring devices, props, cards, and text scale in the main world.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'main_world.metaphor_stage',
    displayName: 'Main Animated World metaphor stage',
    category: 'main_world',
    filePath: '/c4sight/assets/main-world/metaphor-stage.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Reusable stage for contained visual metaphor beats such as the alien wizard misunderstanding.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'host.base',
    displayName: 'Host character base',
    category: 'host',
    filePath: '/c4sight/assets/host/host-base.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Primary C4Sight host/presenter asset used across main world and teaching transitions.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.expression.neutral',
    displayName: 'Host neutral expression',
    category: 'host',
    filePath: '/c4sight/assets/host/expression-neutral.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Neutral host expression for baseline explanation and held shots.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.expression.curious',
    displayName: 'Host curious expression',
    category: 'host',
    filePath: '/c4sight/assets/host/expression-curious.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Curious host expression for questions and “let’s unpack this” moments.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.expression.sceptical',
    displayName: 'Host sceptical expression',
    category: 'host',
    filePath: '/c4sight/assets/host/expression-sceptical.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Sceptical host expression for hype checks and overclaim corrections.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.expression.concerned',
    displayName: 'Host concerned expression',
    category: 'host',
    filePath: '/c4sight/assets/host/expression-concerned.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Concerned host expression for risk, trust, and human judgement beats.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.expression.reassuring',
    displayName: 'Host reassuring expression',
    category: 'host',
    filePath: '/c4sight/assets/host/expression-reassuring.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reassuring host expression for practical resets and takeaways.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.blackboard.pointing',
    displayName: 'Host blackboard pointing pose',
    category: 'host',
    filePath: '/c4sight/assets/host/blackboard-pointing.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Host pose for “Let’s take it to the blackboard” and diagram emphasis.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.blackboard.writing',
    displayName: 'Host blackboard writing pose',
    category: 'host',
    filePath: '/c4sight/assets/host/blackboard-writing.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Host pose for board writing in Blackboard Teaching Mode.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'host.blackboard.listening',
    displayName: 'Host blackboard listening pose',
    category: 'host',
    filePath: '/c4sight/assets/host/blackboard-listening.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Host pose for held teaching moments while narration carries nuance.',
    fallbackComponent: 'HostAssetPlaceholder',
  },
  {
    id: 'blackboard_mode.style_frame',
    displayName: 'Blackboard Teaching Mode style frame',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/style-frame.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Approved blackboard look used only for deeper explanations after the blackboard ritual.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'blackboard_mode.board_background',
    displayName: 'Blackboard Teaching Mode board background',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/board-background.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Board surface and texture for teaching mode.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'blackboard_mode.teaching_layout_reference',
    displayName: 'Blackboard Teaching Mode layout reference',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/teaching-layout-reference.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Title, diagram, side note, host, and caption zones for blackboard scenes.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'blackboard_mode.chalk_dust_overlay',
    displayName: 'Blackboard chalk dust overlay',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/chalk-dust-overlay.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Texture overlay for board scenes only.',
    fallbackComponent: 'TextureAssetPlaceholder',
  },
  {
    id: 'blackboard_mode.model_box',
    displayName: 'Blackboard model box',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/model-box.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reusable model box for simplified AI explanations.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'blackboard_mode.data_patterns_output_diagram',
    displayName: 'Data to patterns to useful output diagram',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/data-patterns-output-diagram.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Core Episode 1 teaching diagram for simple AI explanation.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'interface_mode.style_frame',
    displayName: 'Interface / Tool Mode style frame',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/style-frame.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Approved C4Sight interface style for prompts, outputs, documents, workflows, and tools.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.tool_window',
    displayName: 'Interface / Tool Mode tool window',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/tool-window.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reusable UI window/container for practical AI tool demonstrations.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.cursor_and_selection',
    displayName: 'Interface / Tool Mode cursor and selection states',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/cursor-and-selection.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Cursor, caret, highlight, selection, and click states.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.prompt_card',
    displayName: 'Interface prompt card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/prompt-card.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Reusable prompt card for practical examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'interface_mode.output_card',
    displayName: 'Interface output card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/output-card.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Reusable AI output card for practical examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'interface_mode.interface_ui_cards',
    displayName: 'Interface UI cards',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/interface-ui-cards.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'General interface card system for prompts, outputs, and tool states.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'interface_mode.stylised_document_panel',
    displayName: 'Stylised document panel',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/stylised-document-panel.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Document panel for summaries, assignments, PDFs, and analysis examples.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.workflow_nodes',
    displayName: 'Workflow nodes',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/workflow-nodes.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Nodes and connectors for workflow, tool, and automation explanations.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.toolbox_workflow',
    displayName: 'Toolbox workflow',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/toolbox-workflow.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Interface-mode version of AI as a collection of tools.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.verification_ui_state',
    displayName: 'Verification UI state',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/verification-ui-state.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'UI state for fact-checking, sources, citations, and confidence checks.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'interface_mode.draft_output_card',
    displayName: 'Draft output card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/draft-output-card.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Draft output card for practical examples such as emails and plans.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'human_judgement_mode.style_frame',
    displayName: 'Human Judgement / Real-World Mode style frame',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/human-judgement-mode/style-frame.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes:
      'Approved grounded visual mode for decisions, consequences, trust, and practical context.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'human_judgement_mode.decision_scene_keyframe',
    displayName: 'Human Judgement / Real-World decision keyframe',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/human-judgement-mode/decision-scene-keyframe.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reference keyframe for judgement overriding or checking AI output.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'human_judgement_mode.everyday_background',
    displayName: 'Everyday real-world background',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/human-judgement-mode/everyday-background.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Grounded everyday context background for non-business examples.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'human_judgement_mode.business_background',
    displayName: 'Business real-world background',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/human-judgement-mode/business-background.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Practical business context background for decisions and risk.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'human_judgement_mode.classroom_background',
    displayName: 'Classroom real-world background',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/human-judgement-mode/classroom-background.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Student/school context background for education examples.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'human_judgement_mode.risk_choice_scene',
    displayName: 'Risk choice scene',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/human-judgement-mode/risk-choice-scene.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Grounded choice moment for trust, verification, and practical judgement.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'recurring.verify_stamp',
    displayName: 'Verify Stamp',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/verify-stamp.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Recurring stamp for claims, facts, citations, and “check this” moments.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.cabinet_of_caveats',
    displayName: 'Cabinet of Caveats',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/cabinet-of-caveats.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Recurring device for nuance, exceptions, and “yes, but” context.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.toolbox',
    displayName: 'Toolbox',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/toolbox.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Recurring device for AI as practical tools instead of a mysterious mind.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.confidently_wrong_office_worker',
    displayName: 'Confidently Wrong Office Worker',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/confidently-wrong-office-worker.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Recurring character/device for plausible but incorrect AI answers.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.scam_guru',
    displayName: 'Scam Guru',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/scam-guru.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Recurring device for AI hype, miracle claims, and bad business advice.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.tiny_person_machine',
    displayName: 'Tiny person in machine cross-out',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/tiny-person-machine.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Misconception visual for “AI is not a tiny person inside the machine.”',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.brain_thinking_crossout',
    displayName: 'Human-thinking cross-out',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/brain-thinking-crossout.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Misconception visual for “AI is not thinking exactly like a human.”',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'recurring.blind_trust_crossout',
    displayName: 'Blind-trust cross-out',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/blind-trust-crossout.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Warning visual for “do not blindly trust AI.”',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.neutral',
    displayName: 'Tiny Alien Wizard neutral',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/neutral.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Tiny Alien Wizard baseline pose.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.confident',
    displayName: 'Tiny Alien Wizard confident',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/confident.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Overconfident magic-helper pose for the opening misunderstanding.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.confused',
    displayName: 'Tiny Alien Wizard confused',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/confused.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Confused reaction after the “AI is not magic” correction.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.sad',
    displayName: 'Tiny Alien Wizard sad',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/sad.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Sad reaction and walk-off setup.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.overwhelmed',
    displayName: 'Tiny Alien Wizard overwhelmed',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/overwhelmed.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Overloaded pose for the capability accumulation beat.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.excited',
    displayName: 'Tiny Alien Wizard excited',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/excited.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Curiosity returning after nuance appears.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.freeze',
    displayName: 'Tiny Alien Wizard freeze',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/freeze.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Freeze reaction for the hard correction beat.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.walking_away',
    displayName: 'Tiny Alien Wizard walking away',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/walking-away.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Disappointed walk-off gag pose.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.running_back',
    displayName: 'Tiny Alien Wizard running back',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/running-back.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Excited return when nuance makes the explanation interesting again.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.peeking',
    displayName: 'Tiny Alien Wizard peeking',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/peeking.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Subtle peek-in for “it can feel like magic” callbacks.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.holding_wand',
    displayName: 'Tiny Alien Wizard holding wand',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/characters/alien-wizard/holding-wand.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Opening staged joke pose with wand.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'mascot_wizard.wizard_chalk_wand',
    displayName: 'Wizard chalk wand',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/recurring-devices/wizard-chalk-wand.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reusable wand prop for Tiny Alien Wizard beats.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'transition.blackboard_ritual_transition',
    displayName: 'Blackboard ritual transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/blackboard-ritual-transition.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Primary ritual transition for “Let’s take it to the blackboard.”',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'transition.take_to_blackboard_transition',
    displayName: 'Take to blackboard transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/take_to_blackboard_transition.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Transition from Main Animated World into Blackboard Teaching Mode.',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'transition.board_roll_in',
    displayName: 'Board roll-in transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/board_roll_in.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Physical board entrance for teaching-mode setup.',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'transition.chalk_dust_wipe',
    displayName: 'Chalk dust wipe transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/chalk_dust_wipe.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Soft board-mode wipe for transitions and resets.',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'transition.mascot_points_to_board',
    displayName: 'Mascot points to board transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/mascot_points_to_board.svg',
    preferredFormat: 'svg',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Character-led cue that motivates the board appearing.',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'transition.world_to_board_zoom',
    displayName: 'World to board zoom transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/world_to_board_zoom.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Zoom transition from main world into board explanation space.',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'transition.eraser_wipe',
    displayName: 'Eraser wipe transition',
    category: 'transitions',
    filePath: '/c4sight/assets/transitions/eraser_wipe.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reset wipe for clearing teaching content.',
    fallbackComponent: 'TransitionAssetPlaceholder',
  },
  {
    id: 'audio.two_chalk_taps',
    displayName: 'Two chalk taps audio cue',
    category: 'audio_identity',
    filePath: '/c4sight/assets/audio-identity/two-chalk-taps.wav',
    preferredFormat: 'wav',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Audio identity cue for the blackboard ritual.',
    fallbackComponent: 'AudioAssetPlaceholder',
  },
  {
    id: 'audio.verify_stamp_hit',
    displayName: 'Verify stamp hit audio cue',
    category: 'audio_identity',
    filePath: '/c4sight/assets/audio-identity/verify-stamp-hit.wav',
    preferredFormat: 'wav',
    required: false,
    usageNotes: 'Optional audio identity for Verify Stamp moments.',
    fallbackComponent: 'AudioAssetPlaceholder',
  },
  {
    id: 'audio.blackboard_transition_scribble',
    displayName: 'Blackboard transition scribble audio cue',
    category: 'audio_identity',
    filePath: '/c4sight/assets/audio-identity/blackboard-transition-scribble.wav',
    preferredFormat: 'wav',
    required: false,
    usageNotes: 'Optional sound texture for blackboard transition moments.',
    fallbackComponent: 'AudioAssetPlaceholder',
  },
  {
    id: 'card.email',
    displayName: 'Email card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/email.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for emails.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.website',
    displayName: 'Website card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/website.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for websites.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.assignment',
    displayName: 'Assignment card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/assignment.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for assignments.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.code',
    displayName: 'Code card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/code.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for code.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.image',
    displayName: 'Image card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/image.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for images.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.summary',
    displayName: 'Summary card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/summary.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for summaries.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.business-idea',
    displayName: 'Business idea card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/business-idea.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability/example card for business ideas.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.writing',
    displayName: 'Writing capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/writing.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for writing.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.summarising',
    displayName: 'Summarising capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/summarising.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for summarising.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.coding',
    displayName: 'Coding capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/coding.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for coding.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.explaining',
    displayName: 'Explaining capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/explaining.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for explaining.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.planning',
    displayName: 'Planning capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/planning.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for planning.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.documents',
    displayName: 'Documents capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/documents.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for analysing documents.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.tools',
    displayName: 'Tools capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/tools.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for using tools.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.workflows',
    displayName: 'Workflows capability card',
    category: 'interface_mode',
    filePath: '/c4sight/assets/cards/workflows.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Overwhelm beat card for automating workflows.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'prop.wand',
    displayName: 'Wizard wand prop',
    category: 'mascot_wizard',
    filePath: '/c4sight/assets/recurring-devices/wizard-chalk-wand.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Legacy prop alias for the Show Bible wizard chalk wand.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.saucepan',
    displayName: 'Saucepan prop',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/props/saucepan.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional surreal gag prop for controlled hook bursts.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.bucket',
    displayName: 'Bucket prop',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/props/bucket.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional prop from earlier gag tests.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.laptop',
    displayName: 'Laptop prop',
    category: 'main_world',
    filePath: '/c4sight/assets/props/laptop.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Main-world prop for “inside your laptop” metaphors.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.eraser',
    displayName: 'Eraser prop',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/props/eraser.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Blackboard Teaching Mode reset prop.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.magnifying-glass',
    displayName: 'Magnifying glass prop',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/magnifying-glass.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Verification/checking icon or prop.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'prop.warning',
    displayName: 'Warning icon prop',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/warning.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Warning icon for risk and judgement beats.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'prop.checklist',
    displayName: 'Checklist prop',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/checklist.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Checklist icon for practical use and verification.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'prop.tiny-person-machine',
    displayName: 'Tiny person in machine',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/tiny-person-machine.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Legacy prop alias for tiny person misconception.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'prop.brain-thinking',
    displayName: 'Brain thinking cross-out',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/recurring-devices/brain-thinking-crossout.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Legacy prop alias for human-thinking misconception.',
    fallbackComponent: 'RecurringDeviceAssetPlaceholder',
  },
  {
    id: 'prop.autocomplete-line',
    displayName: 'Autocomplete line',
    category: 'interface_mode',
    filePath: '/c4sight/assets/interface-mode/autocomplete-line.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Simple autocomplete visual that can expand into richer outputs.',
    fallbackComponent: 'ModeAssetPlaceholder',
  },
  {
    id: 'prop.model-box',
    displayName: 'Model box prop',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/blackboard-mode/model-box.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Legacy prop alias for blackboard model box.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'effect.poof',
    displayName: 'Poof effect',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/effects/poof.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional light humour effect. Should not compensate for weak staging.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.spark',
    displayName: 'Spark effect',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/effects/spark.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional small magic-feeling effect for alien wizard beats.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.freeze-burst',
    displayName: 'Freeze burst effect',
    category: 'recurring_devices',
    filePath: '/c4sight/assets/effects/freeze-burst.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional freeze-hit effect for comedic correction beats.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.eraser-smear',
    displayName: 'Eraser smear effect',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/effects/eraser-smear.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Optional board-mode wipe texture.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.circle-highlight',
    displayName: 'Circle highlight effect',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/effects/circle-highlight.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional blackboard highlight effect.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.underline',
    displayName: 'Underline effect',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/effects/underline.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional blackboard underline effect.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.cross-out',
    displayName: 'Cross-out effect',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/effects/cross-out.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional blackboard cross-out effect.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'icon.writing',
    displayName: 'Writing icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/writing.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for writing.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.summarising',
    displayName: 'Summarising icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/summarising.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for summarising.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.coding',
    displayName: 'Coding icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/coding.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for coding.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.explaining',
    displayName: 'Explaining icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/explaining.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for explaining.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.researching',
    displayName: 'Researching icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/researching.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for research/document investigation.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.automating',
    displayName: 'Automating icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/automating.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for automating workflows.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.image-generation',
    displayName: 'Image generation icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/image-generation.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for image generation.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.planning',
    displayName: 'Planning icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/planning.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for planning.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.verification',
    displayName: 'Verification icon',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/verification.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Verification icon for facts, sources, and confidence checks.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.hallucination',
    displayName: 'Hallucination icon',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/hallucination.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional icon for plausible but wrong answers.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.judgement',
    displayName: 'Human judgement icon',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/judgement.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Human judgement icon for responsible use moments.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.trust-risk',
    displayName: 'Trust risk icon',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/trust-risk.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Trust/risk icon for caveats and decision points.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.agents',
    displayName: 'Agents icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/agents.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional future icon for agents.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.connectors',
    displayName: 'Connectors icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/connectors.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional future icon for connectors.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.mcp',
    displayName: 'MCP icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/mcp.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional future icon for MCP/server concepts.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.privacy',
    displayName: 'Privacy icon',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/icons/privacy.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional privacy icon for data and safety episodes.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.roadmap',
    displayName: 'Roadmap icon',
    category: 'main_world',
    filePath: '/c4sight/assets/icons/roadmap.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Roadmap icon for episode structure and series previews.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.documents',
    displayName: 'Documents icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/documents.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for analysing documents.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.tools',
    displayName: 'Tools icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/tools.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for tool use.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.workflows',
    displayName: 'Workflows icon',
    category: 'interface_mode',
    filePath: '/c4sight/assets/icons/workflows.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Capability icon for workflows and automations.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'character.mascot.neutral',
    displayName: 'Legacy mascot neutral pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/neutral.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components. Use host or mascot_wizard assets for new production.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.confident',
    displayName: 'Legacy mascot confident pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/confident.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.confused',
    displayName: 'Legacy mascot confused pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/confused.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.sad',
    displayName: 'Legacy mascot sad pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/sad.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.overwhelmed',
    displayName: 'Legacy mascot overwhelmed pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/overwhelmed.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.excited',
    displayName: 'Legacy mascot excited pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/excited.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.walking-away',
    displayName: 'Legacy mascot walking away pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/walking-away.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.running-back',
    displayName: 'Legacy mascot running back pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/running-back.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.presenting',
    displayName: 'Legacy mascot presenting pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/presenting.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.pointing',
    displayName: 'Legacy mascot pointing pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/pointing.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.holding-prop',
    displayName: 'Legacy mascot holding prop pose',
    category: 'host',
    filePath: '/c4sight/assets/characters/mascot/holding-prop.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Compatibility alias for older preview components.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'scene.cold-open-hook',
    displayName: 'Episode 1 magic misunderstanding keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-magic-misunderstanding.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Episode 1 staged hook keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.magic-chaos',
    displayName: 'Contained magic misunderstanding keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-magic-misunderstanding.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Compatibility alias for older chaos preview scenes.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.no-freeze',
    displayName: 'Not magic freeze keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-not-magic-correction.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Freeze correction keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.not-magic-correction',
    displayName: 'Not magic correction keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-not-magic-correction.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Episode 1 correction keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.not-autocomplete',
    displayName: 'Autocomplete expansion keyframe',
    category: 'interface_mode',
    filePath: '/c4sight/assets/scene-keyframes/episode01-autocomplete-expansion.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Keyframe showing autocomplete expanding into more capable outputs.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.surprising-not-magical',
    displayName: 'Surprising not magical keyframe',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/scene-keyframes/episode01-what-is-ai.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Teaching keyframe for surprising capability without mysticism.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.overwhelm',
    displayName: 'Overwhelm beat keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-overwhelm-beat.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Capability accumulation and reset keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.walk-off-gag',
    displayName: 'Walk-off gag keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-not-magic-correction.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Compatibility alias for older walk-off gag scene.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.return-reveal',
    displayName: 'Return reveal keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-magic-misunderstanding.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Compatibility alias for older nuance return scene.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.slow-down-reset',
    displayName: 'Slow down reset keyframe',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/scene-keyframes/episode01-blackboard-ritual.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Reset keyframe before “What actually is AI?”',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.teaching-diagram',
    displayName: 'What is AI teaching diagram keyframe',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/scene-keyframes/episode01-what-is-ai.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Core blackboard teaching keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.myth-reality',
    displayName: 'Myth vs reality keyframe',
    category: 'blackboard_mode',
    filePath: '/c4sight/assets/scene-keyframes/myth-reality.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Optional comparison scene keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.warning',
    displayName: 'Verify warning keyframe',
    category: 'human_judgement_mode',
    filePath: '/c4sight/assets/scene-keyframes/episode01-verify-warning.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Fact-checking and human judgement keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.roadmap',
    displayName: 'Episode 1 roadmap keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/episode01-roadmap.png',
    preferredFormat: 'png',
    required: true,
    episode1Minimum: true,
    usageNotes: 'Episode 1 roadmap keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.outro',
    displayName: 'C4Sight outro keyframe',
    category: 'main_world',
    filePath: '/c4sight/assets/scene-keyframes/outro.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Optional outro keyframe.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
] as const satisfies readonly C4SightAssetDefinition[];

export type C4SightManifestAsset = (typeof c4sightAssetManifest)[number];
export type C4SightAssetId = C4SightManifestAsset['id'];

export const c4sightAssetManifestById = Object.fromEntries(
  c4sightAssetManifest.map((asset) => [asset.id, asset]),
) as Record<C4SightAssetId, C4SightManifestAsset>;
