import {videoLayout} from '../layout/blackboardLayout';

const showBiblePalette = {
  void: '#0F1011',
  background: '#0F1011',
  surface: '#1A1B1E',
  voidSurface: '#1A1B1E',
  wizardPurple: '#B49FCC',
  hostWhite: '#F0EDE4',
  chalk: '#F4EDE0',
  verifyRed: '#D7382C',
  thesisTeal: '#1A6B5C',
  paper: '#EFE7D6',
  ink: '#221F1F',
} as const;

export const c4sightTokens = {
  source: {
    showBible: 'docs/C4Sight-Show-Bible.md',
    figmaMakeFileKey: 'dkTT6PWK7M5s2GvUF9GZcs',
    figmaMakeUrl:
      'https://www.figma.com/make/dkTT6PWK7M5s2GvUF9GZcs/C4Sight-Animated-Explainer-Board?t=0cRPeIg5uW01zKTo-1',
    localSourcePack: 'reference/figma-make-source',
    boards: [
      'BrandBoard',
      'CharacterBible',
      'PropLibrary',
      'IconSystem',
      'SceneSystem',
      'AnimationGrammar',
      'EpisodeStoryboard',
      'SeriesRoadmap',
      'ExportSpec',
    ],
  },
  canvas: {
    width: videoLayout.width,
    height: videoLayout.height,
    fps: videoLayout.fps,
    aspectRatio: '16:9',
  },
  palette: showBiblePalette,
  mainWorld: {
    background: showBiblePalette.background,
    foreground: showBiblePalette.hostWhite,
    surface: showBiblePalette.surface,
    line: showBiblePalette.chalk,
    accent: showBiblePalette.wizardPurple,
  },
  blackboardMode: {
    background: showBiblePalette.surface,
    foreground: showBiblePalette.chalk,
    surface: showBiblePalette.surface,
    line: showBiblePalette.chalk,
    dust: showBiblePalette.chalk,
  },
  interfaceMode: {
    background: showBiblePalette.background,
    foreground: showBiblePalette.chalk,
    surface: showBiblePalette.surface,
    line: showBiblePalette.chalk,
    accent: showBiblePalette.verifyRed,
  },
  humanJudgementMode: {
    background: showBiblePalette.thesisTeal,
    foreground: showBiblePalette.hostWhite,
    surface: showBiblePalette.thesisTeal,
    line: showBiblePalette.hostWhite,
    accent: showBiblePalette.verifyRed,
  },
  verifyStamp: {
    fill: showBiblePalette.verifyRed,
    stroke: showBiblePalette.verifyRed,
    text: showBiblePalette.hostWhite,
  },
  wizard: {
    fill: showBiblePalette.wizardPurple,
    stroke: showBiblePalette.ink,
    chalkStroke: showBiblePalette.chalk,
  },
  colors: {
    background: showBiblePalette.background,
    surface: showBiblePalette.surface,
    wizardPurple: showBiblePalette.wizardPurple,
    hostWhite: showBiblePalette.hostWhite,
    chalk: showBiblePalette.chalk,
    verifyRed: showBiblePalette.verifyRed,
    thesisTeal: showBiblePalette.thesisTeal,
    paper: showBiblePalette.paper,
    ink: showBiblePalette.ink,
  },
  lineWeights: {
    secondary: 1.75,
    detail: 2,
    main: 2.5,
    bold: 3,
    emphasis: 3.5,
  },
  typography: {
    titleFamily: '"Fraunces", "Playfair Display", Georgia, serif',
    bodyFamily:
      '"DM Sans", "Plus Jakarta Sans", Inter, system-ui, sans-serif',
    captionFamily: '"DM Sans", Inter, system-ui, sans-serif',
    chalkHandFamily: '"Caveat", "Patrick Hand", cursive',
    weights: {
      title: 800,
      body: 700,
      caption: 650,
      annotation: 650,
    },
    sizes: {
      tiny: 22,
      caption: 34,
      annotation: 36,
      label: 38,
      body: 46,
      subtitle: 58,
      title: 86,
      hero: 116,
    },
    lineHeight: {
      tight: 1.08,
      normal: 1.22,
      loose: 1.34,
    },
  },
  layout: {
    safeMargin: 120,
    mobileSafeMargin: 180,
    focusArea: {x: 96, y: 72, width: 1728, height: 936},
    title: {x: 150, y: 92, width: 1620, height: 150},
    character: {x: 230, y: 260, width: 780, height: 570},
    characterCenter: {x: 760, y: 330, width: 400, height: 430},
    main: {x: 180, y: 270, width: 1560, height: 560},
    sideNote: {x: 1250, y: 300, width: 450, height: 390},
    propZone: {x: 1250, y: 270, width: 490, height: 550},
    caption: {x: 240, y: 862, width: 1440, height: 140},
    watermark: {x: 1540, y: 86, width: 250, height: 82},
    cardGap: 34,
    diagramGap: 72,
  },
  sceneZones: {
    titleTopPercent: 0.15,
    characterMiddlePercent: 0.6,
    subtitleBottomPercent: 0.12,
    mobileCriticalPercent: 0.9,
  },
  assetDimensions: {
    mascot: {width: 120, height: 160},
    prop: {width: 80, height: 80},
    icon: {width: 48, height: 48},
    scene: {width: 1920, height: 1080},
  },
  timing: {
    quick: 12,
    transition: 15,
    ritual: 60,
    poseChange: 21,
    writeWord: 15,
    writeFast: 18,
    writeNormal: 28,
    writeSlow: 42,
    drawFast: 18,
    drawNormal: 28,
    drawSlow: 44,
    reaction: 24,
    freeze: 18,
    holdShort: 60,
    holdMedium: 120,
    comedicHold: 72,
    eraser: 28,
    calmReset: 32,
  },
} as const;

export type C4SightTokens = typeof c4sightTokens;
export type C4SightAccent = 'verifyRed' | 'wizardPurple';
