export type C4SightAssetCategory =
  | 'character'
  | 'prop'
  | 'icon'
  | 'scene-keyframe'
  | 'texture'
  | 'card'
  | 'effect';

export type C4SightAssetFormat = 'svg' | 'png';

export type C4SightAssetFallback =
  | 'MascotAssetPlaceholder'
  | 'PropAssetPlaceholder'
  | 'IconAssetPlaceholder'
  | 'CardAssetPlaceholder'
  | 'SceneKeyframePlaceholder'
  | 'TextureAssetPlaceholder'
  | 'EffectAssetPlaceholder';

export type C4SightAssetDefinition = {
  id: string;
  displayName: string;
  category: C4SightAssetCategory;
  filePath: string;
  preferredFormat: C4SightAssetFormat;
  required: boolean;
  usageNotes: string;
  fallbackComponent: C4SightAssetFallback;
};

export const c4sightAssetManifest = [
  {
    id: 'character.mascot.neutral',
    displayName: 'Mascot neutral pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/neutral.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Primary mascot base pose for calm teaching frames.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.confident',
    displayName: 'Mascot confident pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/confident.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for setup jokes and teacher-introduction beats.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.confused',
    displayName: 'Mascot confused pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/confused.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used when the narrator punctures a misconception.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.sad',
    displayName: 'Mascot sad pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/sad.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for disappointed walk-off gags.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.overwhelmed',
    displayName: 'Mascot overwhelmed pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/overwhelmed.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Needed for the capability overload beat.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.excited',
    displayName: 'Mascot excited pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/excited.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for return beats and playful curiosity.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.walking-away',
    displayName: 'Mascot walking away pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/walking-away.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for sad exit and comedic release beats.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.running-back',
    displayName: 'Mascot running back pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/running-back.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for re-entry excitement after a correction.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.presenting',
    displayName: 'Mascot presenting pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/presenting.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used beside teaching diagrams and roadmap cards.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.pointing',
    displayName: 'Mascot pointing pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/pointing.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used to direct attention to one board element.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.mascot.holding-prop',
    displayName: 'Mascot holding prop pose',
    category: 'character',
    filePath: '/c4sight/assets/characters/mascot/holding-prop.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used when the mascot carries a wand, card, eraser, or tool.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.neutral',
    displayName: 'Alien wizard neutral expression',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/neutral.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Hero gag character for the cold open and hook bursts.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.confident',
    displayName: 'Alien wizard confident expression',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/confident.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Starts the magic misunderstanding gag.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.confused',
    displayName: 'Alien wizard confused expression',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/confused.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used after the NO beat.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.sad',
    displayName: 'Alien wizard sad expression',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/sad.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for disappointed drift/walk-off.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.excited',
    displayName: 'Alien wizard excited expression',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/excited.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used when curiosity returns.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.freeze',
    displayName: 'Alien wizard freeze reaction',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/freeze.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Held reaction for the NO freeze moment.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.walking-away',
    displayName: 'Alien wizard walking away',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/walking-away.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for sad exit gag.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.running-back',
    displayName: 'Alien wizard running back',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/running-back.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for excited return beat.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'character.alien-wizard.peeking',
    displayName: 'Alien wizard peeking',
    category: 'character',
    filePath: '/c4sight/assets/characters/alien-wizard/peeking.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional subtle re-entry pose for nuance beats.',
    fallbackComponent: 'MascotAssetPlaceholder',
  },
  {
    id: 'prop.wand',
    displayName: 'Magic wand prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/wand.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Core hook prop; must support cross-out and droop staging.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.saucepan',
    displayName: 'Saucepan prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/saucepan.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Surreal gag prop, used sparingly.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.bucket',
    displayName: 'Bucket prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/bucket.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional physical-comedy prop for later episodes.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.laptop',
    displayName: 'Laptop prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/laptop.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used in the tiny-alien-inside-laptop misconception.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.eraser',
    displayName: 'Board eraser prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/eraser.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for reset transitions and visual cleanup.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.magnifying-glass',
    displayName: 'Magnifying glass prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/magnifying-glass.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for fact-checking and research beats.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.warning',
    displayName: 'Warning triangle prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/warning.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for safety, hallucination, and risk frames.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.checklist',
    displayName: 'Checklist prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/checklist.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for practical takeaway lists.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.tiny-person-machine',
    displayName: 'Tiny person in machine crossed-out prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/tiny-person-machine.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Required for Episode 1 misconception correction.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.brain-thinking',
    displayName: 'Human brain/thinking icon prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/brain-thinking.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used to clarify AI is not human thinking.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.autocomplete-line',
    displayName: 'Autocomplete line prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/autocomplete-line.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used in the not-just-autocomplete teaching beat.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'prop.model-box',
    displayName: 'Model box prop',
    category: 'prop',
    filePath: '/c4sight/assets/props/model-box.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Core teaching diagram element for data to output scenes.',
    fallbackComponent: 'PropAssetPlaceholder',
  },
  {
    id: 'card.email',
    displayName: 'Email task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/email.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.website',
    displayName: 'Website task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/website.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.assignment',
    displayName: 'Assignment task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/assignment.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.code',
    displayName: 'Code task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/code.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.image',
    displayName: 'Image task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/image.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.summary',
    displayName: 'Summary task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/summary.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples and generic summary card.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.business-idea',
    displayName: 'Business idea task card',
    category: 'card',
    filePath: '/c4sight/assets/cards/business-idea.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'One of the opening capability examples.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.writing',
    displayName: 'Writing capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/writing.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.summarising',
    displayName: 'Summarising capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/summarising.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.coding',
    displayName: 'Coding capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/coding.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.explaining',
    displayName: 'Explaining capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/explaining.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.planning',
    displayName: 'Planning capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/planning.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.documents',
    displayName: 'Documents capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/documents.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.tools',
    displayName: 'Tools capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/tools.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'card.workflows',
    displayName: 'Automating workflows capability card',
    category: 'card',
    filePath: '/c4sight/assets/cards/workflows.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability overload section.',
    fallbackComponent: 'CardAssetPlaceholder',
  },
  {
    id: 'effect.poof',
    displayName: 'Chalk poof effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/poof.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used in the opening hook and quick gag beats.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.spark',
    displayName: 'Chalk spark effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/spark.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used around wand and emphasis beats.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.freeze-burst',
    displayName: 'Freeze burst effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/freeze-burst.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used on the NO freeze hit.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.eraser-smear',
    displayName: 'Eraser smear effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/eraser-smear.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Used for transitions from overwhelm to calm teaching.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.circle-highlight',
    displayName: 'Circle highlight effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/circle-highlight.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional designed replacement for procedural chalk circles.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.underline',
    displayName: 'Underline effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/underline.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional designed replacement for procedural underlines.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'effect.cross-out',
    displayName: 'Cross-out effect',
    category: 'effect',
    filePath: '/c4sight/assets/effects/cross-out.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Optional designed replacement for procedural cross-outs.',
    fallbackComponent: 'EffectAssetPlaceholder',
  },
  {
    id: 'texture.blackboard-base',
    displayName: 'Blackboard base texture',
    category: 'texture',
    filePath: '/c4sight/assets/textures/blackboard-base.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Premium dark board texture with no gradients or neon.',
    fallbackComponent: 'TextureAssetPlaceholder',
  },
  {
    id: 'texture.chalk-dust-overlay',
    displayName: 'Chalk dust overlay texture',
    category: 'texture',
    filePath: '/c4sight/assets/textures/chalk-dust-overlay.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Subtle repeatable chalk dust/noise overlay.',
    fallbackComponent: 'TextureAssetPlaceholder',
  },
  {
    id: 'texture.eraser-smear',
    displayName: 'Eraser smear texture',
    category: 'texture',
    filePath: '/c4sight/assets/textures/eraser-smear.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Optional smear texture for wipe transitions.',
    fallbackComponent: 'TextureAssetPlaceholder',
  },
  {
    id: 'texture.chalk-line',
    displayName: 'Chalk line texture',
    category: 'texture',
    filePath: '/c4sight/assets/textures/chalk-line.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Optional stroke texture for masked line rendering.',
    fallbackComponent: 'TextureAssetPlaceholder',
  },
  {
    id: 'scene.cold-open-hook',
    displayName: 'Episode 1 cold open hook keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/cold-open-hook.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Key art for opening AI magic question.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.magic-chaos',
    displayName: 'Magic misunderstanding chaos keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/magic-chaos.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Controlled gag keyframe with cards, wand, alien wizard, and saucepan.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.no-freeze',
    displayName: 'NO freeze keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/no-freeze.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Clean readable NO beat with disappointed reactions.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.not-magic-correction',
    displayName: 'Not magic correction keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/not-magic-correction.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Tiny person, human thinking, and blind trust corrections.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.not-autocomplete',
    displayName: 'Not just autocomplete keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/not-autocomplete.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Autocomplete line expanding into richer outputs.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.surprising-not-magical',
    displayName: 'Surprising not magical keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/surprising-not-magical.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Model box, internal scribbles, magnifier, and question marks.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.overwhelm',
    displayName: 'Capability overwhelm keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/overwhelm.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Mascot overloaded by capability cards before reset.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.walk-off-gag',
    displayName: 'Walk-off gag keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/walk-off-gag.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Sad gag exit after the correction beat.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.return-reveal',
    displayName: 'Return reveal keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/return-reveal.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Curious return beat for nuance after the joke.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.slow-down-reset',
    displayName: 'Slow down reset keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/slow-down-reset.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Calm reset into the first real teaching question.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.teaching-diagram',
    displayName: 'Teaching diagram keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/teaching-diagram.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Clean Data to Patterns to Useful output teaching diagram.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.myth-reality',
    displayName: 'Myth vs reality keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/myth-reality.png',
    preferredFormat: 'png',
    required: false,
    usageNotes: 'Reusable split scene for myth correction frames.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.warning',
    displayName: 'Warning scene keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/warning.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Fact-check warning and human judgement scene.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.roadmap',
    displayName: 'Episode roadmap keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/roadmap.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'Roadmap for the first episode topics.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'scene.outro',
    displayName: 'C4Sight outro keyframe',
    category: 'scene-keyframe',
    filePath: '/c4sight/assets/scene-keyframes/outro.png',
    preferredFormat: 'png',
    required: true,
    usageNotes: 'C4Sight end card: AI explained clearly.',
    fallbackComponent: 'SceneKeyframePlaceholder',
  },
  {
    id: 'icon.writing',
    displayName: 'Writing icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/writing.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for writing.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.summarising',
    displayName: 'Summarising icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/summarising.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for summarising.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.coding',
    displayName: 'Coding icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/coding.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for coding.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.explaining',
    displayName: 'Explaining icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/explaining.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for explaining.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.researching',
    displayName: 'Researching icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/researching.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for research and checking.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.automating',
    displayName: 'Automating icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/automating.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for workflow automation.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.image-generation',
    displayName: 'Image generation icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/image-generation.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for generated images.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.planning',
    displayName: 'Planning icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/planning.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Capability icon for planning.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.verification',
    displayName: 'Verification icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/verification.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for check-it/fact-check moments.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.hallucination',
    displayName: 'Hallucination/caution icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/hallucination.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used when explaining factual risk.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.judgement',
    displayName: 'Human judgement icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/judgement.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for human decision-making emphasis.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.trust-risk',
    displayName: 'Trust/risk icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/trust-risk.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for do-not-blindly-trust beats.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.agents',
    displayName: 'Agents icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/agents.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Episode roadmap and later agents section.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.connectors',
    displayName: 'Connectors icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/connectors.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Episode roadmap and later connectors section.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.mcp',
    displayName: 'MCP icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/mcp.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Episode roadmap and later MCP section.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.privacy',
    displayName: 'Data privacy icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/privacy.svg',
    preferredFormat: 'svg',
    required: false,
    usageNotes: 'Later privacy/safety section.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
  {
    id: 'icon.roadmap',
    displayName: 'Roadmap icon',
    category: 'icon',
    filePath: '/c4sight/assets/icons/roadmap.svg',
    preferredFormat: 'svg',
    required: true,
    usageNotes: 'Used for episode overview.',
    fallbackComponent: 'IconAssetPlaceholder',
  },
] as const satisfies readonly C4SightAssetDefinition[];

export type C4SightAssetId = (typeof c4sightAssetManifest)[number]['id'];
export type C4SightManifestAsset = (typeof c4sightAssetManifest)[number];

export const c4sightAssetManifestById = Object.fromEntries(
  c4sightAssetManifest.map((asset) => [asset.id, asset]),
) as Record<C4SightAssetId, (typeof c4sightAssetManifest)[number]>;

export const getC4SightAssetsByCategory = (category: C4SightAssetCategory) =>
  c4sightAssetManifest.filter((asset) => asset.category === category);

export const getC4SightRequiredAssets = () =>
  c4sightAssetManifest.filter((asset) => asset.required);
